// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LikedResponse struct {
	Success bool `json:"success"`
	Matched bool `json:"matched"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
